title: Gernot Spelsberg
description: Dipl.-Ing. (FH) Elektrotechnik/Ausbilder/Dozent
author: Gernot Spelsberg
avatar: /logo.png
email: gsbildung@mailbox.org
subscribe: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
  #username: newline65
  #card: summary
logo: logo.png
social: false
  name: Gernot Spelsberg
  links:
    #- https://twitter.com/newline65
    #- https://www.facebook.com/ngzhio
    #- https://github.com/gsbildung
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: de
